### 1. Розгортаємо датасет, формуємо датафрейм за допомогою бібліотеки Pandas, виводимо опис полів

In [1]:
import pandas as pd

pd.set_option('display.max_columns', None)

df = pd.read_csv(r'C:\Users\Руслана\Downloads\dataset_salary_NEW.csv', encoding='utf-8', low_memory=False)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450 entries, 0 to 449
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Показник                     450 non-null    object
 1   Період                       450 non-null    object
 2   Стать                        450 non-null    object
 3   Територіальний розріз        450 non-null    object
 4   Категорія розрізу            450 non-null    object
 5   Розріз                       450 non-null    object
 6   Періодичність                450 non-null    object
 7   Одиниця виміру               450 non-null    object
 8   Масштабування                450 non-null    object
 9   Кількість десяткових знаків  450 non-null    object
 10  Спеціальне значення даних    24 non-null     object
 11  Примітки набору даних        0 non-null      float64
 12  Примітки часового ряду       450 non-null    object
 13  Примітки спостереження       4 non-null      object
 14  2016                         431 non-null    float64
 15  2017                         0 non-null      float64
 16  2018                         0 non-null      float64
 17  2019                         0 non-null      float64
 18  2020                         429 non-null    float64
dtypes: float64(6), object(13)
memory usage: 66.9+ KB

### 2. Виводимо перші 5 рядків датафрейму для ознайомлення

In [2]:
df.head()

,Показник,Період,Стать,Територіальний розріз,Категорія розрізу,Розріз,Періодичність,Одиниця виміру,Масштабування,Кількість десяткових знаків,Спеціальне значення даних,Примітки набору даних,Примітки часового ряду,Примітки спостереження,2016,2017,2018,2019,2020
0,"Нараховано в середньому штатному працівнику, з...",Місяць,Жінки,Україна,Професії та професійні групи,Вищі посадові особи громадських і самоврядну-...,Річна,Гривня,Одиниці,Нуль,NaN,NaN,1. Дані підготовлено за результатами державног...,NaN,6514.0,NaN,NaN,NaN,25298.0
1,"Нараховано в середньому штатному працівнику, з...",Місяць,Жінки,Україна,Професії та професійні групи,Фахівці в галузі біології та агрономії,Річна,Гривня,Одиниці,Нуль,NaN,NaN,1. Дані підготовлено за результатами державног...,NaN,3264.0,NaN,NaN,NaN,8872.0
2,"Нараховано в середньому штатному працівнику, з...",Місяць,Жінки,Україна,Вікова група,55-59 років,Річна,Гривня,Одиниці,Нуль,NaN,NaN,1. Дані підготовлено за результатами державног...,NaN,4219.0,NaN,NaN,NaN,9459.0
3,"Нараховано в середньому штатному працівнику, з...",Місяць,Жінки,Україна,Професії та професійні групи,Професіонали в галузі наук про життя та медичн...,Річна,Гривня,Одиниці,Нуль,NaN,NaN,1. Дані підготовлено за результатами державног...,NaN,4362.0,NaN,NaN,NaN,10637.0
4,"Нараховано в середньому штатному працівнику, з...",Місяць,Жінки,Україна,Професії та професійні групи,Професіонали в галузі релігії,Річна,Гривня,Одиниці,Нуль,NaN,NaN,1. Дані підготовлено за результатами державног...,NaN,2265.0,NaN,NaN,NaN,2941.0

### Питання для дослідження:
Які відмінності в рівні заробітної плати працівників в Україні спостерігалися у 2016 та 2020 роках залежно від статі, рівня освіти, вікової категорії, стажу роботи, професії та виду економічної діяльності?

**Гіпотези:**

- **Освіта:** рівень заробітної плати відрізняється залежно від рівня освіти та загалом є вищим серед працівників із вищим рівнем освіти. 
- **Вік:** рівень заробітної плати відрізняється між віковими групами та зростає до певної вікової категорії, після чого може стабілізуватися або знижуватися. 
- **Стаж:** працівники з більшим стажем мають вищий рівень заробітної плати.
- **Професія:** рівень зарплати суттєво відрізняється між професійними групами.
- **Вид діяльності:** рівень заробітної плати суттєво відрізняється між видами економічної діяльності. 
- **Стать:** рівень заробітної плати відрізняється між чоловіками та жінками, причому середня заробітна плата чоловіків є вищою.

### 3. Визначення даних для аналізу

Згідно з **питанням дослідження** та сформованими **гіпотезами**, визначаємо, які дані з датасету використовуємо для подальшого аналізу:

- **Територіальний розріз** — залишаємо значення **«Україна»**, оскільки аналіз проводиться на рівні всієї країни без розбиття за регіонами.

- **Категорія розрізу** — залишаємо такі категорії:
  - **«Професії та професійні групи»**
  - **«Вікова група»**
  - **«Вид економічної діяльності»**
  - **«Рівень освіти»**
  - **«Стаж роботи»**

- **Стать** — залишаємо значення **"Чоловіки"** та **"Жінки"** для дослідження рівня заробітної плати по гендерному розподілу.

In [3]:
# Перевіримо дані по визначеним розрізам для аналізу. Зробимо копію датасету, де залишимо дані, потрібні для дослідження.

df_clean = df.copy()

categories = [
    'Професії та професійні групи',
    'Вікова група',
    'Вид економічної діяльності',
    'Рівень освіти',
    'Стаж роботи'
]

df_clean = df[
    (df['Територіальний розріз'] == 'Україна') &
    (df['Стать'].isin(['Жінки', 'Чоловіки'])) &
    (df['Категорія розрізу'].isin(categories))
].copy()

In [4]:
# Перевірка даних після фільтрації
print('Кількість рядків після фільтрації:', len(df_clean))

print('\nТериторіальний розріз:')
print(df_clean['Територіальний розріз'].value_counts())

print('\nСтать:')
print(df_clean['Стать'].value_counts())

print('\nКатегорія розрізу:')
print(df_clean['Категорія розрізу'].value_counts())

Кількість рядків після фільтрації: 450

Територіальний розріз:
Територіальний розріз
Україна    450
Name: count, dtype: int64

Стать:
Стать
Жінки       225
Чоловіки    225
Name: count, dtype: int64

Категорія розрізу:
Категорія розрізу
Професії та професійні групи    358
Вид економічної діяльності       42
Рівень освіти                    20
Вікова група                     16
Стаж роботи                      14
Name: count, dtype: int64

In [5]:
# Перевіряємо пусті значення у даних
print(df_clean.isna().sum())

Показник                         0
Період                           0
Стать                            0
Територіальний розріз            0
Категорія розрізу                0
Розріз                           0
Періодичність                    0
Одиниця виміру                   0
Масштабування                    0
Кількість десяткових знаків      0
Спеціальне значення даних      426
Примітки набору даних          450
Примітки часового ряду           0
Примітки спостереження         446
2016                            19
2017                           450
2018                           450
2019                           450
2020                            21
dtype: int64

In [6]:
# Видаляємо повністю пусті колонки, які не несуть цінності для дослідження

df_clean = df_clean.drop(columns=[
    '2017',
    '2018',
    '2019',
    'Примітки набору даних'
])

In [7]:
# Перевіряємо дані після видалення пустих колонок

print(df_clean.isna().sum())

Показник                         0
Період                           0
Стать                            0
Територіальний розріз            0
Категорія розрізу                0
Розріз                           0
Періодичність                    0
Одиниця виміру                   0
Масштабування                    0
Кількість десяткових знаків      0
Спеціальне значення даних      426
Примітки часового ряду           0
Примітки спостереження         446
2016                            19
2020                            21
dtype: int64

In [8]:
# Бачимо з попереднього результату, що є пропуски в колонках 2016 та 2020, що потрібні нам для дослідження.
# Тому робимо перевірку пустих значень з виводом додаткової інформації по цим полям, чи не зазначено причину пропуску
df_clean[df_clean['2016'].isna() | df_clean['2020'].isna()][[
    'Категорія розрізу',
    'Розріз',
    'Спеціальне значення даних',
    'Примітки часового ряду',
    'Примітки спостереження',
    '2016',
    '2020'
]]

,Категорія розрізу,Розріз,Спеціальне значення даних,Примітки часового ряду,Примітки спостереження,2016,2020
26,Професії та професійні групи,Законодавці,Явищ не було,1. Дані підготовлено за результатами державног...,NaN,NaN,41034.0
56,Рівень освіти,Докторантура або її еквівалент,NaN,1. Дані підготовлено за результатами державног...,Інформація відсутня.,NaN,16911.0
76,Професії та професійні групи,"Фахівці, що практикують в галузі нетрадиційної...",NaN,1. Дані підготовлено за результатами державног...,NaN,10831.0,NaN
100,Рівень освіти,Дошкільна освіта,Явищ не було,1. Дані підготовлено за результатами державног...,NaN,NaN,NaN
107,Професії та професійні групи,"Робітники рибного промислу, мисливці та мислив...",Явищ не було,1. Дані підготовлено за результатами державног...,NaN,NaN,5590.0
109,Професії та професійні групи,"Допоміжний персонал релігійних організацій, як...",Явищ не було,1. Дані підготовлено за результатами державног...,NaN,1472.0,NaN
117,Професії та професійні групи,Найпростіші професії з чищення взуття та інших...,Явищ не було,1. Дані підготовлено за результатами державног...,NaN,NaN,5091.0
120,Професії та професійні групи,Фахівці з бродильного виробництва та виноробства,Явищ не було,1. Дані підготовлено за результатами державног...,NaN,NaN,7246.0
153,Професії та професійні групи,Фахівці з виробництва молочних продуктів,Явищ не було,1. Дані підготовлено за результатами державног...,NaN,NaN,10769.0
168,Професії та професійні групи,Астрологи та ворожки,NaN,1. Дані підготовлено за результатами державног...,NaN,3610.0,NaN
208,Професії та професійні групи,Фахівці з переробки плодоовочевої продукції,NaN,1. Дані підготовлено за результатами державног...,NaN,2534.0,NaN
212,Професії та професійні групи,Інші фахівці в галузі харчової та переробної п...,Явищ не було,1. Дані підготовлено за результатами державног...,NaN,NaN,7345.0
221,Професії та професійні групи,Манекенники та інші моделі,Явищ не було,1. Дані підготовлено за результатами державног...,NaN,NaN,NaN
238,Рівень освіти,Дошкільна освіта,Явищ не було,1. Дані підготовлено за результатами державног...,NaN,NaN,NaN
273,Рівень освіти,Докторантура або її еквівалент,NaN,1. Дані підготовлено за результатами державног...,Інформація відсутня.,NaN,18815.0
280,Професії та професійні групи,Професіонали з безпеки та якості,Явищ не було,1. Дані підготовлено за результатами державног...,NaN,9822.0,NaN
297,Професії та професійні групи,Законодавці,Явищ не було,1. Дані підготовлено за результатами державног...,NaN,NaN,40322.0
307,Професії та професійні групи,Фахівці з дошкільного виховання,Явищ не було,1. Дані підготовлено за результатами державног...,NaN,3685.0,NaN
323,Професії та професійні групи,"Фахівці, що практикують в галузі нетрадиційної...",Явищ не було,1. Дані підготовлено за результатами державног...,NaN,NaN,NaN
340,Професії та професійні групи,"Продавці, що ведуть торгівлю з лотків та на ри...",Явищ не було,1. Дані підготовлено за результатами державног...,NaN,1525.0,NaN
353,Професії та професійні групи,Соціальні працівники,Явищ не було,1. Дані підготовлено за результатами державног...,NaN,1883.0,NaN
355,Професії та професійні групи,Астрологи та ворожки,Явищ не було,1. Дані підготовлено за результатами державног...,NaN,NaN,NaN
359,Професії та професійні групи,Найпростіші професії з чищення взуття та інших...,Явищ не було,1. Дані підготовлено за результатами державног...,NaN,1730.0,NaN
362,Професії та професійні групи,Фахівці з виробництва молочних продуктів,Явищ не було,1. Дані підготовлено за результатами державног...,NaN,NaN,NaN
393,Професії та професійні групи,Фахівці з бродильного виробництва та виноробства,Явищ не було,1. Дані підготовлено за результатами державног...,NaN,NaN,NaN
401,Професії та професійні групи,Фахівці зі зберігання та переробки зерна,Явищ не було,1. Дані підготовлено за результатами державног...,NaN,2511.0,NaN
404,Професії та професійні групи,Манекенники та інші моделі,NaN,1. Дані підготовлено за результатами державног...,NaN,628.0,NaN
425,Професії та професійні групи,"Фахівці з виробництва борошняних, кондитерськи...",Явищ не було,1. Дані підготовлено за результатами державног...,NaN,NaN,NaN
428,Професії та професійні групи,Фахівці з переробки плодоовочевої продукції,Явищ не було,1. Дані підготовлено за результатами державног...,NaN,NaN,NaN
431,Професії та професійні групи,Інші фахівці в галузі харчової та переробної п...,Явищ не було,1. Дані підготовлено за результатами державног...,NaN,NaN,NaN

In [9]:
# Опрацювання відсутніх даних. Створюємо окремий статус для пропусків

df_clean['Причина пропуску'] = 'Немає пропусків'

# 1. Явищ не було
df_clean.loc[
    df_clean['Спеціальне значення даних'].eq('Явищ не було'),
    'Причина пропуску'
] = 'Явищ не було'

# 2. Інформація відсутня
df_clean.loc[
    df_clean['Спеціальне значення даних'].eq('Інформація відсутня.') |
    df_clean['Примітки спостереження'].eq('Інформація відсутня.'),
    'Причина пропуску'
] = 'Інформація відсутня'

# 3. Пропуск є, але причина не зазначена
df_clean.loc[
    (
        df_clean['2016'].isna() |
        df_clean['2020'].isna()
    ) &
    (df_clean['Причина пропуску'] == 'Немає пропусків'),
    'Причина пропуску'
] = 'Причина не зазначена'

In [10]:
# Перевіряємо інформацію після присвоєння статусу для пропущених значень щоб дізнатися для скількох з них причина пропуску була вказана
print(
    df_clean.loc[
        df_clean['2016'].isna() | df_clean['2020'].isna(),
        'Причина пропуску'
    ].value_counts()
)

Причина пропуску
Явищ не було            24
Причина не зазначена     4
Інформація відсутня      2
Name: count, dtype: int64

Пропуски не замінюємо на 0.
NaN залишаємо як NaN, а причину зберігаємо окремим полем **Причина пропуску**.

## 4. Перевіряємо гранулярність

**Бажана гранулярність:**

Категорія розрізу → Розріз → Стать → одне спостереження за 2016 та 2020 роки

In [11]:
granularity_cols = [
    'Категорія розрізу',
    'Розріз',
    'Стать'
]

In [12]:
# Перевіряємо наявність дублікатів

duplicates = df_clean[
    df_clean.duplicated(
        subset=granularity_cols,
        keep=False
    )
]

print('Кількість дубльованих рядків:', len(duplicates))

Кількість дубльованих рядків: 8

In [13]:
# Перевіряємо, які саме дублікати є в датасеті
duplicate_counts = (
    df_clean
    .groupby(
        ['Категорія розрізу', 'Розріз', 'Стать'],
        dropna=False
    )
    .size()
    .reset_index(name='Кількість')
)

print(
    duplicate_counts[
        duplicate_counts['Кількість'] > 1
    ].to_string(index=False)
)

           Категорія розрізу                                                               Розріз    Стать  Кількість
Професії та професійні групи Інші професійні назви робіт кваліфікованих робітників з інструментом    Жінки          2
Професії та професійні групи Інші професійні назви робіт кваліфікованих робітників з інструментом Чоловіки          2
Професії та професійні групи                       Керівники підприємств, установ та організацій     Жінки          2
Професії та професійні групи                       Керівники підприємств, установ та організацій  Чоловіки          2

In [14]:
# Детальніше дослідження дублікатів для порівняння
print(
    duplicates[
        [
            'Стать',
            'Категорія розрізу',
            'Розріз',
            '2016',
            '2020',
            'Спеціальне значення даних',
            'Примітки часового ряду',
            'Примітки спостереження'
        ]
    ]
    .sort_values(
        ['Розріз', 'Стать']
    )
    .to_string(index=False)
)

   Стать            Категорія розрізу                                                               Розріз   2016    2020 Спеціальне значення даних                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Примітки часового ряду Примітки спостереження
   Жінки Професії та професійні групи Інші професійні назви робіт кваліфікованих робітників з інструментом 4958.0 10977.0                       NaN                                                                                                                             1. Дані підготовлено за результатами державного статистичного спостереження "Рівень заробітної плати працівників за статтю, віком, освітою та професійними групами", яким охоплені юридичні особи та відокремлені підрозділи юридичних осіб із кількістю найманих працівників 10 і більше осіб. 2. Дані наведено без урахування тимчасово окупованої території Автономної Республіки Крим, м. Севастополя та частини тимчасово окупованих територій у Донецькій та Луганській областях. 3. Середньомісячна заробітна плата одного штатного працівника розраховується шляхом ділення нарахованого фонду оплати праці штатних працівників за звітний місяць (період) на середньооблікову кількість штатних працівників і на кількість місяців у періоді. Професія – це певний вид трудової діяльності, який потребує спеціальних теоретичних знань та практичних навичок. Професія – рід занять, певна форма трудової діяльності.                    NaN
   Жінки Професії та професійні групи Інші професійні назви робіт кваліфікованих робітників з інструментом 4958.0 10977.0                       NaN 1. Дані підготовлено за результатами державного статистичного спостереження "Рівень заробітної плати працівників за статтю, віком, освітою та професійними групами", яким охоплені юридичні особи та відокремлені підрозділи юридичних осіб із кількістю найманих працівників 10 і більше осіб. 2. Дані наведено без урахування тимчасово окупованої території Автономної Республіки Крим, м. Севастополя та частини тимчасово окупованих територій у Донецькій та Луганській областях. 3. Середня заробітна плата штатних працівників за одну оплачену годину  обчислюється шляхом ділення суми нарахованого фонду оплати праці штатних працівників на кількість оплачених їм людино-годин за відповідний період. Професія – це певний вид трудової діяльності, який потребує спеціальних теоретичних знань та практичних навичок. Професія – рід занять, певна форма трудової діяльності. 4. За 2016 рік дані наведено за класом "Бригадир на дільницях основного виробництва (інші кваліфіковані роботи)" відповідно Класифікатора професій ДК 003:2005.                    NaN
Чоловіки Професії та професійні групи Інші професійні назви робіт кваліфікованих робітників з інструментом 3924.0 11952.0                       NaN 1. Дані підготовлено за результатами державного статистичного спостереження "Рівень заробітної плати працівників за статтю, віком, освітою та професійними групами", яким охоплені юридичні особи та відокремлені підрозділи юридичних осіб із кількістю найманих працівників 10 і більше осіб. 2. Дані наведено без урахування тимчасово окупованої території Автономної Республіки Крим, м. Севастополя та частини тимчасово окупованих територій у Донецькій та Луганській областях. 3. Середня заробітна плата штатних працівників за одну оплачену годину  обчислюється шляхом ділення суми нарахованого фонду оплати праці штатних працівників на кількість оплачених їм людино-годин за відповідний період. Професія – це певний вид трудової діяльності, який потребує спеціальних теоретичних знань та практичних навичок. Професія – рід занять, певна форма трудової діяльності. 4. За 2016 рік дані наведено за класом "Бригадир на дільницях основного виробництва (інші кваліфіковані роботи)" відповідно Класифікатора професій ДК 003:2005.                    NaN
Чоловіки Професії та професійні групи Інші професійні назви робіт кваліфікованих робітників з інструментом 3924.0 11952.0                       NaN                                                                                                                             1. Дані підготовлено за результатами державного статистичного спостереження "Рівень заробітної плати працівників за статтю, віком, освітою та професійними групами", яким охоплені юридичні особи та відокремлені підрозділи юридичних осіб із кількістю найманих працівників 10 і більше осіб. 2. Дані наведено без урахування тимчасово окупованої території Автономної Республіки Крим, м. Севастополя та частини тимчасово окупованих територій у Донецькій та Луганській областях. 3. Середньомісячна заробітна плата одного штатного працівника розраховується шляхом ділення нарахованого фонду оплати праці штатних працівників за звітний місяць (період) на середньооблікову кількість штатних працівників і на кількість місяців у періоді. Професія – це певний вид трудової діяльності, який потребує спеціальних теоретичних знань та практичних навичок. Професія – рід занять, певна форма трудової діяльності.                    NaN
   Жінки Професії та професійні групи                       Керівники підприємств, установ та організацій  6865.0 15151.0                       NaN                                                                                                                             1. Дані підготовлено за результатами державного статистичного спостереження "Рівень заробітної плати працівників за статтю, віком, освітою та професійними групами", яким охоплені юридичні особи та відокремлені підрозділи юридичних осіб із кількістю найманих працівників 10 і більше осіб. 2. Дані наведено без урахування тимчасово окупованої території Автономної Республіки Крим, м. Севастополя та частини тимчасово окупованих територій у Донецькій та Луганській областях. 3. Середньомісячна заробітна плата одного штатного працівника розраховується шляхом ділення нарахованого фонду оплати праці штатних працівників за звітний місяць (період) на середньооблікову кількість штатних працівників і на кількість місяців у періоді. Професія – це певний вид трудової діяльності, який потребує спеціальних теоретичних знань та практичних навичок. Професія – рід занять, певна форма трудової діяльності.                    NaN
   Жінки Професії та професійні групи                       Керівники підприємств, установ та організацій  6613.0 16074.0                       NaN                                                                                                                             1. Дані підготовлено за результатами державного статистичного спостереження "Рівень заробітної плати працівників за статтю, віком, освітою та професійними групами", яким охоплені юридичні особи та відокремлені підрозділи юридичних осіб із кількістю найманих працівників 10 і більше осіб. 2. Дані наведено без урахування тимчасово окупованої території Автономної Республіки Крим, м. Севастополя та частини тимчасово окупованих територій у Донецькій та Луганській областях. 3. Середньомісячна заробітна плата одного штатного працівника розраховується шляхом ділення нарахованого фонду оплати праці штатних працівників за звітний місяць (період) на середньооблікову кількість штатних працівників і на кількість місяців у періоді. Професія – це певний вид трудової діяльності, який потребує спеціальних теоретичних знань та практичних навичок. Професія – рід занять, певна форма трудової діяльності.                    NaN
Чоловіки Професії та професійні групи                       Керівники підприємств, установ та організацій  8742.0 18481.0                       NaN                                                                                                                             1. Дані підготовлено за результатами державного статистичного спостереження "Рівень заробітної плати працівників за статтю, віком, освітою та професійними групами", яким охоплені юридичні особи та відокремлені підрозділи юридичних осіб із кількістю найманих працівників 10 і більше осіб. 2. Дані наведено без урахування тимчасово окупованої території Автономної Республіки Крим, м. Севастополя та частини тимчасово окупованих територій у Донецькій та Луганській областях. 3. Середньомісячна заробітна плата одного штатного працівника розраховується шляхом ділення нарахованого фонду оплати праці штатних працівників за звітний місяць (період) на середньооблікову кількість штатних працівників і на кількість місяців у періоді. Професія – це певний вид трудової діяльності, який потребує спеціальних теоретичних знань та практичних навичок. Професія – рід занять, певна форма трудової діяльності.                    NaN
Чоловіки Професії та професійні групи                       Керівники підприємств, установ та організацій  9452.0 18095.0                       NaN                                                                                                                             1. Дані підготовлено за результатами державного статистичного спостереження "Рівень заробітної плати працівників за статтю, віком, освітою та професійними групами", яким охоплені юридичні особи та відокремлені підрозділи юридичних осіб із кількістю найманих працівників 10 і більше осіб. 2. Дані наведено без урахування тимчасово окупованої території Автономної Республіки Крим, м. Севастополя та частини тимчасово окупованих територій у Донецькій та Луганській областях. 3. Середньомісячна заробітна плата одного штатного працівника розраховується шляхом ділення нарахованого фонду оплати праці штатних працівників за звітний місяць (період) на середньооблікову кількість штатних працівників і на кількість місяців у періоді. Професія – це певний вид трудової діяльності, який потребує спеціальних теоретичних знань та практичних навичок. Професія – рід занять, певна форма трудової діяльності.                    NaN

## Висновок щодо дублікатів

**Під час перевірки дублікатів виявлено два типи неоднозначних спостережень, для яких прийнято рішення про виключення з аналізу:**

- **«Інші професійні назви робіт кваліфікованих робітників з інструментом»**

- один рядок містить дані про середньомісячну заробітну плату;
- другий — дані про середню заробітну плату за одну оплачену годину.

Погодинне спостереження видаляємо, оскільки в межах цього дослідження аналізується саме середньомісячна заробітна плата.

- **«Керівники підприємств, установ та організацій»**

два спостереження мають однакові **Категорія розрізу**, **Розріз**, **Стать** та **Примітки**;
при цьому значення заробітної плати за 2016 та 2020 роки відрізняються;
у даних відсутнє пояснення причини такої розбіжності.

Через недостатність інформації неможливо достовірно визначити, яке з двох значень є коректним. Тому обидва спостереження виключено з аналізу, щоб уникнути необґрунтованого вибору даних та потенційного спотворення результатів дослідження.

In [15]:
# 1. Видаляємо погодинні спостереження
mask_hourly = (
    (df_clean['Категорія розрізу'] == 'Професії та професійні групи') &
    (df_clean['Розріз'] == 'Інші професійні назви робіт кваліфікованих робітників з інструментом') &
    df_clean['Примітки часового ряду'].str.contains(
        'за одну оплачену годину',
        na=False
    )
)

# 2. Видаляємо неоднозначні спостереження щодо керівників
mask_ambiguous = (
    (df_clean['Категорія розрізу'] == 'Професії та професійні групи') &
    (df_clean['Розріз'].str.strip() == 'Керівники підприємств, установ та організацій')
)

# Видаляємо визначені дублікати
df_clean = df_clean.loc[
    ~(mask_hourly | mask_ambiguous)
].copy()

print('Кількість рядків після видалення:', len(df_clean))

Кількість рядків після видалення: 444

In [16]:
# Перевірка пропусків після очищення
print('Пропуски після очищення:')
print(
    df_clean.isna()
    .sum()
    .sort_values(ascending=False)
)

Пропуски після очищення:
Примітки спостереження         440
Спеціальне значення даних      420
2020                            21
2016                            19
Показник                         0
Період                           0
Стать                            0
Територіальний розріз            0
Категорія розрізу                0
Розріз                           0
Періодичність                    0
Одиниця виміру                   0
Масштабування                    0
Кількість десяткових знаків      0
Примітки часового ряду           0
Причина пропуску                 0
dtype: int64

In [17]:
# Перевірка пропусків, де значення відсутні в обох роках досліджень, так як ці дані не несуть жодної інформації про рівень зарплати
df_clean.loc[
    df_clean['2016'].isna() & df_clean['2020'].isna(),
    [
        'Стать',
        'Категорія розрізу',
        'Розріз',
        '2016',
        '2020',
        'Причина пропуску'
    ]
].to_string(index=False)

'   Стать            Категорія розрізу                                                                        Розріз  2016  2020 Причина пропуску\n   Жінки                Рівень освіти                                                              Дошкільна освіта   NaN   NaN     Явищ не було\n   Жінки Професії та професійні групи                                                    Манекенники та інші моделі   NaN   NaN     Явищ не було\nЧоловіки                Рівень освіти                                                              Дошкільна освіта   NaN   NaN     Явищ не було\nЧоловіки Професії та професійні групи                       Фахівці, що практикують в галузі нетрадиційної медицини   NaN   NaN     Явищ не було\nЧоловіки Професії та професійні групи                                                          Астрологи та ворожки   NaN   NaN     Явищ не було\nЧоловіки Професії та професійні групи                                      Фахівці з виробництва молочних продуктів   NaN   NaN     Явищ не було\nЧоловіки Професії та професійні групи                              Фахівці з бродильного виробництва та виноробства   NaN   NaN     Явищ не було\nЧоловіки Професії та професійні групи Фахівці з виробництва борошняних, кондитерських виробів та харчоконцентратів\xa0   NaN   NaN     Явищ не було\nЧоловіки Професії та професійні групи                                   Фахівці з переробки плодоовочевої продукції   NaN   NaN     Явищ не було\nЧоловіки Професії та професійні групи                    Інші фахівці в галузі харчової та переробної промисловості   NaN   NaN     Явищ не було'

In [18]:
# Видаляємо рядки без значень за обидва роки досліджень
df_clean = df_clean.dropna(
    subset=['2016', '2020'],
    how='all'
)

print('Кількість рядків після видалення:', len(df_clean))

Кількість рядків після видалення: 434

In [19]:
# Так як для нашого дослідження потрібні повні дані за 2016 і 2020 для порівняння, для датасету з яким будемо працювати надалі,
# видалимо рядки, де є пропущені дані

df_tableau = df_clean.copy()

# Видаляємо рядки, де відсутнє значення за 2016 або 2020
df_tableau = df_tableau.dropna(
    subset=['2016', '2020']
).copy()

print('Кількість рядків:', len(df_tableau))
print('Кількість колонок:', len(df_tableau.columns))

Кількість рядків: 414
Кількість колонок: 16

In [20]:
df_tableau_long = df_tableau.melt(
    id_vars=[
        'Показник',
        'Період',
        'Стать',
        'Територіальний розріз',
        'Категорія розрізу',
        'Розріз',
        'Періодичність',
        'Одиниця виміру',
        'Масштабування',
        'Кількість десяткових знаків',
        'Спеціальне значення даних',
        'Примітки часового ряду',
        'Примітки спостереження',
        'Причина пропуску'
    ],
    value_vars=['2016', '2020'],
    var_name='Рік',
    value_name='Заробітна плата'
)

In [21]:
# Вивантажуємо дані для подальшого опрацювання в tableau

df_tableau_long.to_csv(
   'salary_research_tableau.csv',
   index=False,
   encoding='utf-8-sig',
   sep=';'
)